config/routes.rb
Rails.application.routes.draw do
  resources :groups, except: :show

  resources :uploads, only: %i[index create]

  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships

  validates :name, presence: true

  scope :ordered_by_created_at_asc, -> { order(created_at: :asc) }

  delegate :organizers_full_names, to: :users
end

app/models/group_membership.rb
class GroupMembership < ApplicationRecord
  belongs_to :user
  belongs_to :group

  enum role: { organizer: 0, presenter: 1, participant: 2 }

  validates :user_id, :group_id, :role, presence: true
  validates :role, inclusion: { in: GroupMembership.roles.keys }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :group_memberships, dependent: :destroy
  has_many :groups, through: :group_memberships

  validates :first_name, :last_name, presence: true

  def self.organizers_full_names
    includes(:group_memberships).where(group_memberships: { role: :organizer })
                                .distinct
                                .pluck(Arel.sql("first_name || ' ' || last_name"))
                                .join(", ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    flash[:notice] = "Record not found"
    redirect_to root_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[edit update destroy]
  before_action :set_users, only: %i[new edit]

  def index
    @groups = Group.ordered_by_created_at_asc
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(name: group_params[:name])

    if contains_any_user
      if @group.save
        ImportGroupsService.manage_group_memberships(:create_memberships, @group, group_params)
        redirect_to_groups_path("created")
      else
        respond_to do |format|
          flash.now[:error] = "Unable to create group."
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    else
      render_new_action
    end
  end

  def update
    if contains_any_user
      if @group.update(name: group_params[:name])
        ImportGroupsService.manage_group_memberships(:update_memberships, @group, group_params)
        redirect_to_groups_path("updated")
      else
        respond_to do |format|
          flash.now[:error] = "Unable to update group."
          format.turbo_stream
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    else
      render_new_action
    end
  end

  def destroy
    if @group.destroy
      redirect_to_groups_path("destroyed")
    else
      respond_to do |format|
        flash.now[:error] = "Cannot destroy the group."
        format.turbo_stream
        format.html { redirect_to groups_url, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def set_users
    @users = User.all
  end

  def redirect_to_groups_path(action)
    respond_to do |format|
      flash.now[:success] = "Group #{action} successfully."
      format.turbo_stream
      format.html { redirect_to groups_path, status: :ok }
    end
  end

  def render_new_action
    respond_to do |format|
      flash.now[:error] = "At least one user is required."
      format.turbo_stream
      format.html { render :edit, status: :unprocessable_entity }
    end
  end

  def contains_any_user
    group_params[:organizer].present? || group_params[:presenter].present? ||
    group_params[:participant].present?
  end

  def group_params
    params.require(:group).permit(:name, organizer: [], presenter: [], participant: [])
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
  end

  def create
    if file_exist?
      ImportGroupsService.new(file_param).import_csv
      flash[:success] = "File uploaded"
      redirect_to root_path
    else
      flash[:error] = "File upload failed."
      redirect_to uploads_path
    end
  end

  private

  def file_exist?
    file_param.present? && file_param.content_type.eql?("text/csv")
  end

  def file_param
    params.require(:file_upload)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def membership_roles(group, user)
    group.group_memberships.where(user_id: user.id)
                               .distinct.pluck(:role)
  end

  def organizers_names(group)
    full_names = group.organizers_full_names

    full_names.blank? ? "N/A" : full_names
  end
end

app/views/groups/_form.html.erb
<%= turbo_frame_tag dom_id group do %>
  <div class="p-4 rounded-md bg-indigo-50 m-2">
    <%= form_with(model: group, id: 'form', class: "contents") do |form| %>
      <div class="my-5">
        <%= form.label :group_name %>
        <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
      <div class="bg-white p-4 rounded-md mt-4 border">
        <h2 class="text-lg font-bold text-2xl mb-4">Assign Users</h2>
        <table class="w-full">
          <thead>
            <tr>
              <th class="py-2">First Name</th>
              <th class="py-2">Last Name</th>
              <th class="py-2">Organizer</th>
              <th class="py-2">Presenter</th>
              <th class="py-2">Participant</th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "user", collection: @users, locals: { group: group } %>
          </tbody>
        </table>
      </div>
      <div class="flex justify-center mt-5">
        <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
        <%= link_to "Cancel", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-white inline-block font-medium" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<%= turbo_frame_tag dom_id(group) do %>
  <div class='flex justify-between items-center bg-white m-2 p-6 border border-gray-100 rounded-lg'>
    <p class='w-40'><%= group&.name %></p>
    <p>
      <%= organizers_names(group) %>
    </p>
    <div class='flex'>
      <%= link_to 'Edit', edit_group_path(group), class: 'btn bg-gray-200 p-2 w-20 text-center rounded-md mr-2' %>
      <%= button_to 'Delete', group_path(group), method: :delete, class: 'btn bg-red-100 p-2 w-20 text-center rounded-md mr-2', data: { controller: :dialog, action: 'click->dialog#confirmDelete'} %>
    </div>
  </div>
<% end %>

app/views/groups/_user.html.erb
<tr>
  <td class="px-20 py-2"><%= user.first_name %></td>
  <td class="px-20 py-2"><%= user.last_name %></td>
  <td class="px-20 py-2">
    <%= check_box_tag "group[organizer][]", user.id, membership_roles(group, user).include?('organizer') %>
  </td>
  <td class="px-20 py-2">
    <%= check_box_tag "group[presenter][]", user.id, membership_roles(group, user).include?('presenter') %>
  </td>
  <td class="px-20 py-2">
    <%= check_box_tag "group[participant][]", user.id, membership_roles(group, user).include?('participant') %>
  </td>
</tr>

app/views/groups/create.turbo_stream.erb
<% if @group.persisted? %>
  <%= turbo_stream.replace :new_group do %>
    <%= turbo_frame_tag :new_group %>
  <% end %>
  <%= turbo_stream.append 'groups', partial: 'group', locals: { group: @group } %>
<% end %>
<%= turbo_stream.update('flash', partial: 'layouts/shared/flash') %>

app/views/groups/destroy.turbo_stream.erb
<%= turbo_stream.remove @group %>
<%= turbo_stream.update('flash', partial: 'layouts/shared/flash') %>

app/views/groups/edit.html.erb
<%= turbo_frame_tag dom_id @group do %>
  <%= render 'form', group: @group %>
<% end %>

app/views/groups/index.html.erb
<div class='mt-24 w-full'>
  <div class='m-auto w-4/5'>
    <%= turbo_frame_tag :new_group %>
  </div>
  <%= turbo_stream_from :groups %>
  <div class='m-auto w-4/5'>
    <div class='flex justify-between items-center bg-gray-200 m-2 p-6 border border-gray-100 rounded h-1 font-medium text-lg'>
      <p>Group Name</p>
      <p>Organizers</p>
      <p>Actions</p>
    </div>
    <%= turbo_frame_tag :groups do %>
      <%= render @groups %>
    <% end %>
  </div>
  <div class='bg-gray-200 py-4 text-center'>
    <p>&copy; MeetUp App</p>
  </div>
</div>

app/views/groups/new.html.erb
<%= turbo_frame_tag :new_group do %>
  <%= render 'form', group: @group %>
<% end %>

app/views/groups/update.turbo_stream.erb
<% if @group.errors.blank? %>
  <%= turbo_stream.replace dom_id(@group), partial: 'group', locals: { group: @group } %>
<% end %>
<%= turbo_stream.update('flash', partial: 'layouts/shared/flash') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'inter-font', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'tailwind', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class='flex bg-gray-100 mx-auto mt-2 px-5 font-sans container'>
      <div class='top-28 absolute'>
        <nav class="top-0 left-0 z-20 fixed bg-gray-200 dark:bg-gray-900 border-gray-200 w-full">
          <div class="flex flex-wrap justify-between items-center mx-auto p-4 max-w-screen-xl">
            <a href="/" class="flex items-center">
              <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-8" alt="Flowbite Logo" />
              <span class="self-center font-semibold text-blue-500 text-2xl whitespace-nowrap">MeetUp App</span>
            </a>
            <div class="hidden md:block w-full md:w-auto" id="navbar-default">
              <ul class="flex md:flex-row flex-col md:space-x-8 mt-4 md:mt-0 p-4 md:p-0 md:border-0 dark:border-gray-700 font-medium">
                <li>
                  <%= link_to 'Import from CSV', uploads_path, class: "rounded-lg py-3 px-5 bg-gray-500 text-white flex font-medium"%>
                </li>
                <li>
                  <%= link_to 'View Groups', groups_path, class: "rounded-lg py-3 px-5 bg-gray-500 text-white flex font-medium",data: { 'turbo-frame': 'new_group' }%>
                </li>
                <li>
                  <%= link_to 'Create New group', new_group_path, class: "rounded-lg py-3 px-5 bg-blue-500 text-white flex font-medium",data: { 'turbo-frame': 'new_group' }%>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div class="z-10 absolute flex w-96">
          <turbo-frame id='flash'>
            <%= render 'layouts/shared/flash' %>
          </turbo-frame>
        </div>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<div id="flash-messages flex absolute">
  <% flash.each do |key, value| %>
    <% if key.eql? 'error' %>
      <div class="inline-block z-50 bg-red-50 mb-5 px-3 py-2 rounded-lg font-medium text-red-500" id="alert">
        <%= value %>
      </div>
    <% else %>
      <div class="inline-block z-50 bg-green-50 mb-5 px-3 py-2 rounded-lg font-medium text-green-500" id="notice">
        <%= value %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/uploads/index.html.erb
<div class='top-24 left-36 z-0 absolute bg-gray-100 bg-white shadow-md p-6 rounded-lg w-9/12 h-96'>
  <div class="top-36 left-96 absolute">
    <%= form_tag(uploads_path, method: :post, multipart: true, class: 'mb-4') do %>
      <div class='flex items-center'>
       <%= file_field_tag :file_upload, accept: '.csv', class: 'py-2 px-3 border rounded-md shadow-sm mr-5 bg-white' %>
        <%= submit_tag 'Import Users', class: 'rounded-lg shadow-sm py-3 px-5 bg-blue-500 text-white flex font-medium cursor-pointer'%>
      </div>
    <% end %>
  </div>
</div>